django_projects/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('meTube/', include("video_app.urls")),
    path('meTube/', include("meTube.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meTube/urls.py
from django.urls import include, path
from . import views


app_name = "meTube"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.sign_in_page, name="login"),
    path("signUp", views.signUp, name="signUp"),
    path("signIn", views.signIn, name="signIn"),
    path("signOut", views.signOut, name="signOut"),
    path("profile/<int:user_id>/", include([
        path("", views.profile, name="profile"),
        path("deleteVideo", views.delete_video, name="delete_video")
    ])),
    path("video/", include([
        path("add", views.add_video, name="add_video"),
        path("save", views.save_video, name="save_video"),
        path("<int:video_id>", views.watch_video, name="watch_video"),
        path("updateView", views.update_view, name="update_view")
    ]))
]

meTube/models.py
from django.contrib.auth import *
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _
import os
from django.utils import timezone

def video_upload_path(instance, filename):
    return 'videos/user_{0}/{1}'.format(instance.user.id, filename)
class AppUser(models.Model):

    

    class Meta:
        verbose_name = _("AppUser")
        verbose_name_plural = _("AppUsers")

    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse("AppUser_detail", kwargs={"pk": self.pk})

    first_name = models.CharField(_("First Name"), max_length=256)
    surname = models.CharField(_("Surname"), max_length=256)
    email = models.EmailField(_("Email Address"), max_length=254, unique=True)
    password = models.CharField(_("Password"), max_length=256)
    avatar = models.ImageField(_("Avatar"), upload_to='avatar/', height_field=500, width_field=500, max_length=None, blank=True)
    last_login = models.DateTimeField(_('Last Login'), blank=True, null=True)
    date_created = models.DateTimeField(_("Date Created"), auto_now=False, auto_now_add=True)
    last_modified = models.DateTimeField(_("Date Modified"), auto_now=True, auto_now_add=False)
    
    @property
    def is_authenticated(self):
        """
        Always return True. This is a way to tell if the user has been
        authenticated in templates.
        """
        return True

class Video(models.Model):

    

    class Meta:
        verbose_name = _("Video")
        verbose_name_plural = _("Videos")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Video_detail", kwargs={"pk": self.pk})

    title = models.CharField(_("Title"), max_length=50)
    caption = models.CharField(_("Caption"), max_length=256)
    user = models.ForeignKey("AppUser", verbose_name=_("User"), related_name='user', on_delete=models.CASCADE)
    video = models.FileField(_("Video"), upload_to=video_upload_path, max_length=100)
    active = models.BooleanField(_("Active"), default=True)
    date_added = models.DateTimeField(_("Date Added"), auto_now=False, auto_now_add=True)

class Like(models.Model):

    

    class Meta:
        verbose_name = _("Like")
        verbose_name_plural = _("Likes")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Like_detail", kwargs={"pk": self.pk})

    user = models.ForeignKey("AppUser", verbose_name=_("User"), related_name='like_user', on_delete=models.CASCADE)
    video = models.ForeignKey("Video", verbose_name=_("Video"), related_name='like_video', on_delete=models.CASCADE)
    date = models.DateTimeField(_("Date Added"), auto_now=False, default=timezone.now)

class Comment(models.Model):

    

    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Comment_detail", kwargs={"pk": self.pk})

    user = models.ForeignKey("AppUser", verbose_name=_("User"), related_name='comment_user', on_delete=models.CASCADE)
    comment = models.CharField(_("Comment"), max_length=256)
    video = models.ForeignKey("Video", verbose_name=_("Video"), related_name='comment_video', on_delete=models.CASCADE)
    date = models.DateTimeField(_("Date Added"), auto_now=False, default=timezone.now)

class Reply(models.Model):

    

    class Meta:
        verbose_name = _("Reply")
        verbose_name_plural = _("Replies")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Reply_detail", kwargs={"pk": self.pk})

    user = models.ForeignKey("AppUser", verbose_name=_("User"), related_name='reply_user', on_delete=models.CASCADE)
    comment = models.ForeignKey("Comment", verbose_name=_("Comment"), related_name='reply', on_delete=models.CASCADE)
    date = models.DateTimeField(_("Date Added"), auto_now=False, default=timezone.now)

class View(models.Model):

    

    class Meta:
        verbose_name = _("View")
        verbose_name_plural = _("Views")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("View_detail", kwargs={"pk": self.pk})

    user = models.ForeignKey("AppUser", verbose_name=_("User"), related_name='viewer', on_delete=models.CASCADE)
    video = models.ForeignKey("Video", verbose_name=_("Video"), related_name='viewed_video', on_delete=models.CASCADE)
    date = models.DateTimeField(_("Date Added"), auto_now=False, auto_now_add=True)

meTube/forms.py
from django.forms import ModelForm
from django.forms.widgets import EmailInput, PasswordInput, TextInput, FileInput, Textarea
from meTube.models import AppUser, Video

class SignInForm(ModelForm):
    class Meta:
        model = AppUser
        fields = ['email', 'password']
        widgets = {
            'email': EmailInput(attrs={
                'class': "form-control",
                'id': "floatingEmail",
                'name': "floatingEmail",
                'placeholder': "Email Address"
            }),
            'password': PasswordInput(attrs={
                'class': "form-control",
                'id': "floatingPassword",
                'name': "floatingPassword",
                'placeholder': "Password"
            })
        }

class SignUpForm(ModelForm):
    class Meta:
        model = AppUser
        fields = ['first_name','surname', 'email', 'password']
        widgets = {
            'first_name': TextInput(attrs={
                'class': "form-control",
                'id': "floatingFirstName",
                'name': "floatingFirstName",
                'placeholder': "John"
            }),
            'surname': TextInput(attrs={
                'class': "form-control",
                'id': "floatingSurname",
                'name': "floatingSurname",
                'placeholder': "Doe"
            }),
            'email': EmailInput(attrs={
                'class': "form-control",
                'id': "floatingEmail",
                'name': "floatingEmail",
                'placeholder': "Email Address"
            }),
            'password': PasswordInput(attrs={
                'class': "form-control",
                'id': "floatingPassword",
                'name': "floatingPassword",
                'placeholder': "Password"
            })
        }

class VideoUploadForm(ModelForm):
    class Meta:
        model = Video
        fields = ['title','caption', 'video']
        widgets = {
            'title': TextInput(attrs={
                'class': "form-control",
                'id': "floatingTitle",
                'name': "floatingTitle",
                'placeholder': "Title"
            }),
            'caption': Textarea(attrs={
                'rows': "4",
                'class': "form-control",
                'id': "floatingCaption",
                'name': "floatingCaption",
                'style': "height: auto;",
                'placeholder': "Caption"
            }),
            'video': FileInput(attrs={
                'class': "form-control",
                'id': "floatingVideo",
                'name': "floatingVideo",
            })
        }

meTube/views.py
from django.contrib.auth import authenticate, login, logout
from django.http.response import HttpResponseForbidden, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from .models import AppUser, Video, Comment, Reply, Like, View
from .forms import *
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required


forms = {
    "signInForm": SignInForm,
    "signUpForm": SignUpForm
    }

# Create your views here.
@login_required
def index(request):
    videos = Video.objects.all()
    return render(request, "meTube/index.html", {
        "videos":videos
        })

def sign_in_page(request):
    return render(request, "meTube/login.html", {"forms": forms})

def signUp(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.password = make_password(form.cleaned_data['password'])
            user.save()
            return render(request, "meTube/login.html", {
                "sign_up_status": "ok",
                "forms": forms
            })
    return redirect(reverse('meTube:login'))
    
def signIn(request):
    if request.method == "POST":
        form = SignInForm(request.POST)
        email = form.data["email"]
        password = form.data["password"]
        user = authenticate(request, email = email, password = password)
        if user is not None:
            login(request, user)
            return redirect(reverse('meTube:index'))
        else:
            return render(request, "meTube/login.html", {
                "sign_in_status": "error",
                "forms": forms
            })
    return redirect(reverse('meTube:login'))
    
@login_required
def signOut(request):
    logout(request)
    return render(request, "meTube/login.html", {
        "sign_out_status": "ok",
        "forms": forms
    })
    
@login_required
def profile(request, user_id):
    user = AppUser.objects.get(pk=user_id)
    videos = Video.objects.filter(user=user)
    return render(request, "meTube/profile/index.html", {
        "user": user,
        "videos": videos
    })
    
@login_required
def add_video(request):
    return render(request, "meTube/video/index.html", {
        "videoUploadForm": VideoUploadForm
    })
    
@login_required
def save_video(request):
    if request.method == "POST":
        form = VideoUploadForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            caption = form.cleaned_data['caption']
            video = form.cleaned_data['video']
            user = AppUser.objects.get(pk=int(request.user.id))
            video = Video(title=title, caption=caption, user=user, video=video)
            video.save()
            return redirect(reverse('meTube:profile', args=[request.user.id]))
    else:
        return render(request, "meTube/video/index.html", {
            "status": "error",
            "videoUploadForm": VideoUploadForm
        })
        
@login_required
def delete_video(request,user_id):
    if request.method == "POST" and user_id != request.user.id:
        user = AppUser.objects.get(pk=int(request.user.id))
        video = Video.objects.filter(pk=request.POST.get('video_id'), user=user)
        if video is not None:
            video.delete()
            return JsonResponse({"status": "success"}, status=200)
        else:
            return JsonResponse({"status": "error"}, status=401)
    return HttpResponseForbidden()

@login_required
def watch_video(request, video_id):
    video = Video.objects.get(pk=video_id)
    user = AppUser.objects.get(pk=video.user_id)
    views = View.objects.filter(video=video.id).count()
    return render(request, "meTube/video/watch.html",{
        "video": video,
        "user": user,
        "views": views
    })

def update_view(request):
    if request.is_ajax and request.method == "POST":
        video = Video.objects.get(pk=request.POST.get('video_id'))
        user = AppUser.objects.get(pk=request.POST.get('user_id'))

        if video is not None and user is not None:
            View.objects.create(
                user = user,
                video = video
            )
            return JsonResponse({"status": "success"})
        else:
            return JsonResponse({"status": "video or user not found"}, status=404)
    return JsonResponse({"status": "error"}, status=400)

meTube/templates/meTube/video/index.html
        {% extends "meTube/layouts/home_layout.html" %} {% load static %}
        {% block content %}
        <div class="px-3">
            <div class="card mx-auto mt-4 col-11 col-md-8" style="">
                <div class="card-header bg-dark text-white p-4">
                    <h4>Upload a new video</h4>
                </div>
                <div class="card-body">
                    {% if status == "error" %}
                        <div class="alert alert-danger alert-dismissible fade show d-flex align-items-center w-25 mx-auto mb-4 d-print-none" role="alert">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-check-circle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Success:">
                                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                            </svg>
                            <div>
                                <strong>Video was not uploaded successfully</strong>
                            </div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                    <form action="{% url 'meTube:save_video' %}" method="post" enctype="multipart/form-data" id="videoUploadForm">
                        {% csrf_token %}
                        {% for field in videoUploadForm %}
                            {% if field.label == 'Video' %}
                                {{ field }}
                            {% else %}
                                <div class="form-floating mb-4">
                                    {{ field }}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                </div>
                            {% endif %}
                        {% endfor %}
                        {% comment %} <img class="mb-4" src="{% static 'video_app/img/camera-logo.svg' %}" alt="" width="72" height="57"> {% endcomment %}
                        <button class="w-100 btn btn-lg vid-btn text-white mt-3" type="submit">Upload Video</button>
                    </form>
            </div>
        </div>
        <!-- End -->
        {% endblock %}

meTube/templates/meTube/video/watch.html
        {% extends "meTube/layouts/home_layout.html" %} {% load static %}
        {% block video_player_css %}
            <link rel="stylesheet" href="https://cdn.plyr.io/3.6.8/plyr.css" />
            <link rel="stylesheet" href="{% static 'meTube/css/player.css' %}" />
        {% endblock %}
        {% block video_player_js %}
            <script src="https://cdn.plyr.io/3.6.8/plyr.js"></script>
            <script src="{% static 'meTube/js/player.js' %}"></script>
        {% endblock %}
        {% block content %}
        <div class="px-3">
        {% csrf_token %}
        <input type="hidden" name="video_id" value="{{ video.id }}">
        <input type="hidden" name="user_id" value="{{ request.user.id }}">
            <div class="mx-auto mt-4 col-md-8" style="">
                <video controls crossorigin playsinline
                    data-poster="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.jpg"
                    id="player"
                    class=""
                >
                    <source src="{{ MEDIA_URL }}{{ video.video }}" type="video/mp4" />

                </video>
                <div class="pt-3">
                    <h4>{{ video.title }}</h4>
                    <div class="d-flex align-items-center justify-content-between">
                        <div id="" class="d-flex">
                            <h6>{{ views }} view{{ views|pluralize }}<span class="px-2">.</span>{{ video.date_added|date:"DATE_FORMAT" }}</h6>
                        </div>
                        <div id="like-container" class="d-flex align-items-center">
                            <button id="like-btn" class="btn d-flex py-1 px-2">
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-hand-thumbs-up me-1" viewBox="0 0 16 16">
                                    <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
                                </svg>
                                <h6 id="likes-count">14k</h6>
                            </button>
                        </div>
                    </div>
                    <hr>
                    <a href="{% url 'meTube:profile' user.id %}" class="" style="text-decoration: none; color: inherit;">
                        <figure class="figure d-flex align-items-center">
                            <img class="me-3" id="profile-img" href="#" src="https://ui-avatars.com/api/?name=
                                {{ user.first_name }}+{{ user.surname }}
                                &background=FB9E0C&color=fff&rounded=true&size=48&format=svg"
                            alt="">
                            <figcaption id="user-name" class="figure-caption fs-3 text-dark">
                                {{ user.first_name }} {{ user.surname }}
                            </figcaption>
                        </figure>
                    </a>
                    <div class="ms-5">
                        <div class="ms-3" id="caption-text">
                            <p class="">{{ video.caption }}</p>
                        </div>
                    <div>
                </div>
            </div>
        </div>
        <!-- End -->
        {% endblock %}