django_projects/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('meTube/', include("video_app.urls")),
    path('meTube/', include("meTube.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meTube/urls.py
from django.urls import include, path
from . import views


app_name = "meTube"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.sign_in_page, name="login"),
    path("signUp", views.signUp, name="signUp"),
    path("signIn", views.signIn, name="signIn"),
    path("signOut", views.signOut, name="signOut"),
    path("profile/<int:user_id>/", include([
        path("", views.profile, name="profile"),
        path("deleteVideo", views.delete_video, name="delete_video")
    ])),
    path("video/", include([
        path("add", views.add_video, name="add_video"),
        path("save", views.save_video, name="save_video"),
        path("<int:video_id>", views.watch_video, name="watch_video"),
        path("updateView", views.update_view, name="update_view")
    ]))
]

meTube/models.py
from django.contrib.auth import *
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _
import os
from django.utils import timezone

def video_upload_path(instance, filename):
    return 'videos/user_{0}/{1}'.format(instance.user.id, filename)
class AppUser(models.Model):

    

    class Meta:
        verbose_name = _("AppUser")
        verbose_name_plural = _("AppUsers")

    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse("AppUser_detail", kwargs={"pk": self.pk})

    first_name = models.CharField(_("First Name"), max_length=256)
    surname = models.CharField(_("Surname"), max_length=256)
    email = models.EmailField(_("Email Address"), max_length=254, unique=True)
    password = models.CharField(_("Password"), max_length=256)
    avatar = models.ImageField(_("Avatar"), upload_to='avatar/', height_field=500, width_field=500, max_length=None, blank=True)
    last_login = models.DateTimeField(_('Last Login'), blank=True, null=True)
    date_created = models.DateTimeField(_("Date Created"), auto_now=False, auto_now_add=True)
    last_modified = models.DateTimeField(_("Date Modified"), auto_now=True, auto_now_add=False)
    
    @property
    def is_authenticated(self):
        """
        Always return True. This is a way to tell if the user has been
        authenticated in templates.
        """
        return True

class Video(models.Model):

    

    class Meta:
        verbose_name = _("Video")
        verbose_name_plural = _("Videos")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Video_detail", kwargs={"pk": self.pk})

    title = models.CharField(_("Title"), max_length=50)
    caption = models.CharField(_("Caption"), max_length=256)
    user = models.ForeignKey("AppUser", verbose_name=_("User"), related_name='user', on_delete=models.CASCADE)
    video = models.FileField(_("Video"), upload_to=video_upload_path, max_length=100)
    active = models.BooleanField(_("Active"), default=True)
    date_added = models.DateTimeField(_("Date Added"), auto_now=False, auto_now_add=True)

class Like(models.Model):

    

    class Meta:
        verbose_name = _("Like")
        verbose_name_plural = _("Likes")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Like_detail", kwargs={"pk": self.pk})

    user = models.ForeignKey("AppUser", verbose_name=_("User"), related_name='like_user', on_delete=models.CASCADE)
    video = models.ForeignKey("Video", verbose_name=_("Video"), related_name='like_video', on_delete=models.CASCADE)
    date = models.DateTimeField(_("Date Added"), auto_now=False, default=timezone.now)

class Comment(models.Model):

    

    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Comment_detail", kwargs={"pk": self.pk})

    user = models.ForeignKey("AppUser", verbose_name=_("User"), related_name='comment_user', on_delete=models.CASCADE)
    comment = models.CharField(_("Comment"), max_length=256)
    video = models.ForeignKey("Video", verbose_name=_("Video"), related_name='comment_video', on_delete=models.CASCADE)
    date = models.DateTimeField(_("Date Added"), auto_now=False, default=timezone.now)

class Reply(models.Model):

    

    class Meta:
        verbose_name = _("Reply")
        verbose_name_plural = _("Replies")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Reply_detail", kwargs={"pk": self.pk})

    user = models.ForeignKey("AppUser", verbose_name=_("User"), related_name='reply_user', on_delete=models.CASCADE)
    comment = models.ForeignKey("Comment", verbose_name=_("Comment"), related_name='reply', on_delete=models.CASCADE)
    date = models.DateTimeField(_("Date Added"), auto_now=False, default=timezone.now)

class View(models.Model):

    

    class Meta:
        verbose_name = _("View")
        verbose_name_plural = _("Views")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("View_detail", kwargs={"pk": self.pk})

    user = models.ForeignKey("AppUser", verbose_name=_("User"), related_name='viewer', on_delete=models.CASCADE)
    video = models.ForeignKey("Video", verbose_name=_("Video"), related_name='viewed_video', on_delete=models.CASCADE)
    date = models.DateTimeField(_("Date Added"), auto_now=False, auto_now_add=True)

meTube/forms.py
from django.forms import ModelForm
from django.forms.widgets import EmailInput, PasswordInput, TextInput, FileInput, Textarea
from meTube.models import AppUser, Video

class SignInForm(ModelForm):
    class Meta:
        model = AppUser
        fields = ['email', 'password']
        widgets = {
            'email': EmailInput(attrs={
                'class': "form-control",
                'id': "floatingEmail",
                'name': "floatingEmail",
                'placeholder': "Email Address"
            }),
            'password': PasswordInput(attrs={
                'class': "form-control",
                'id': "floatingPassword",
                'name': "floatingPassword",
                'placeholder': "Password"
            })
        }

class SignUpForm(ModelForm):
    class Meta:
        model = AppUser
        fields = ['first_name','surname', 'email', 'password']
        widgets = {
            'first_name': TextInput(attrs={
                'class': "form-control",
                'id': "floatingFirstName",
                'name': "floatingFirstName",
                'placeholder': "John"
            }),
            'surname': TextInput(attrs={
                'class': "form-control",
                'id': "floatingSurname",
                'name': "floatingSurname",
                'placeholder': "Doe"
            }),
            'email': EmailInput(attrs={
                'class': "form-control",
                'id': "floatingEmail",
                'name': "floatingEmail",
                'placeholder': "Email Address"
            }),
            'password': PasswordInput(attrs={
                'class': "form-control",
                'id': "floatingPassword",
                'name': "floatingPassword",
                'placeholder': "Password"
            })
        }

class VideoUploadForm(ModelForm):
    class Meta:
        model = Video
        fields = ['title','caption', 'video']
        widgets = {
            'title': TextInput(attrs={
                'class': "form-control",
                'id': "floatingTitle",
                'name': "floatingTitle",
                'placeholder': "Title"
            }),
            'caption': Textarea(attrs={
                'rows': "4",
                'class': "form-control",
                'id': "floatingCaption",
                'name': "floatingCaption",
                'style': "height: auto;",
                'placeholder': "Caption"
            }),
            'video': FileInput(attrs={
                'class': "form-control",
                'id': "floatingVideo",
                'name': "floatingVideo",
            })
        }

meTube/views.py
from django.contrib.auth import authenticate, login, logout
from django.http.response import HttpResponseForbidden, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from .models import AppUser, Video, Comment, Reply, Like, View
from .forms import *
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required


forms = {
    "signInForm": SignInForm,
    "signUpForm": SignUpForm
    }

# Create your views here.
@login_required
def index(request):
    videos = Video.objects.all()
    return render(request, "meTube/index.html", {
        "videos":videos
        })

def sign_in_page(request):
    return render(request, "meTube/login.html", {"forms": forms})

def signUp(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.password = make_password(form.cleaned_data['password'])
            user.save()
            return render(request, "meTube/login.html", {
                "sign_up_status": "ok",
                "forms": forms
            })
    return redirect(reverse('meTube:login'))
    
def signIn(request):
    if request.method == "POST":
        form = SignInForm(request.POST)
        email = form.data["email"]
        password = form.data["password"]
        user = authenticate(request, email = email, password = password)
        if user is not None:
            login(request, user)
            return redirect(reverse('meTube:index'))
        else:
            return render(request, "meTube/login.html", {
                "sign_in_status": "error",
                "forms": forms
            })
    return redirect(reverse('meTube:login'))
    
@login_required
def signOut(request):
    logout(request)
    return render(request, "meTube/login.html", {
        "sign_out_status": "ok",
        "forms": forms
    })
    
@login_required
def profile(request, user_id):
    user = AppUser.objects.get(pk=user_id)
    videos = Video.objects.filter(user=user)
    return render(request, "meTube/profile/index.html", {
        "user": user,
        "videos": videos
    })
    
@login_required
def add_video(request):
    return render(request, "meTube/video/index.html", {
        "videoUploadForm": VideoUploadForm
    })
    
@login_required
def save_video(request):
    if request.method == "POST":
        form = VideoUploadForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            caption = form.cleaned_data['caption']
            video = form.cleaned_data['video']
            user = AppUser.objects.get(pk=int(request.user.id))
            video = Video(title=title, caption=caption, user=user, video=video)
            video.save()
            return redirect(reverse('meTube:profile', args=[request.user.id]))
    else:
        return render(request, "meTube/video/index.html", {
            "status": "error",
            "videoUploadForm": VideoUploadForm
        })
        
@login_required
def delete_video(request,user_id):
    if request.method == "POST" and user_id != request.user.id:
        user = AppUser.objects.get(pk=int(request.user.id))
        video = Video.objects.filter(pk=request.POST.get('video_id'), user=user)
        if video is not None:
            video.delete()
            return JsonResponse({"status": "success"}, status=200)
        else:
            return JsonResponse({"status": "error"}, status=401)
    return HttpResponseForbidden()

@login_required
def watch_video(request, video_id):
    video = Video.objects.get(pk=video_id)
    user = AppUser.objects.get(pk=video.user_id)
    views = View.objects.filter(video=video.id).count()
    return render(request, "meTube/video/watch.html",{
        "video": video,
        "user": user,
        "views": views
    })

def update_view(request):
    if request.is_ajax and request.method == "POST":
        video = Video.objects.get(pk=request.POST.get('video_id'))
        user = AppUser.objects.get(pk=request.POST.get('user_id'))

        if video is not None and user is not None:
            View.objects.create(
                user = user,
                video = video
            )
            return JsonResponse({"status": "success"})
        else:
            return JsonResponse({"status": "video or user not found"}, status=404)
    return JsonResponse({"status": "error"}, status=400)

meTube/templates/meTube/layouts/home_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap Icons -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'meTube/css/style.css' %}">
        <!-- Bootstrap CSS -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
            crossorigin="anonymous"
        >
        {% block video_player_css %} {% endblock %}
        <title>MeTube | Home</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark ps-5">
            <div class="container-fluid">
                <a class="navbar-brand fs-4" href="{% url 'meTube:index' %}">MeTube.com</a>
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                    </ul> -->
                    <form class="d-flex mx-auto w-75">
                        <div class="input-group me-5">
                            <input type="text" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="button-addon2">
                            <button class="btn btn-outline-secondary" type="button" id="button-addon2"><span class="mx-2"><i class="bi bi-search"></i></span></button>
                        </div>
                    </form>
                    <div class="d-flex nav-item dropstart me-3">
                        <img class="dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                            role="button" data-bs-toggle="dropdown" aria-expanded="false"
                            src="https://ui-avatars.com/api/?name=
                                {{ request.user.first_name }}+
                                {{ request.user.surname }}&
                                background=D08104&color=fff&rounded=true&format=svg&size=36"
                            alt="">
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'meTube:add_video' %}">Upload Video</a></li>
                            <li><a class="dropdown-item" href="{% url 'meTube:profile' request.user.id %}">Profile</a></li>
                            <li><a class="dropdown-item" href="{% url 'meTube:signOut' %}">Logout</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
        <main class="container-fluid mt-3 mb-5">
            {% block content %} {% endblock %}
        </main>
{% comment %}         
        <footer class="d-flex justify-content-center">
            <p class="mt-5 mb-3 text-muted">By Timilehin Olusegun &copy; 2021.</p>
        </footer> {% endcomment %}
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        {% block video_player_js %}{% endblock %}
        <script src="{% static 'meTube/js/app.js' %}"></script>
    </body>
</html>

meTube/templates/meTube/layouts/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap Icons -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
    />
    <link rel="stylesheet" href="{% static 'meTube/css/styles.css' %}" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
      crossorigin="anonymous"
    />

    <title>MeTube | Home</title>
  </head>

  <body>
    {% block body %} {% endblock %}
    <footer>
      <p class="mt-5 mb-3 text-muted">By Timilehin Olusegun &copy; 2021.</p>
    </footer>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
      crossorigin="anonymous"
    ></script>
  </body>
</html>